// targets.js
// Hardcoded scrape targets for Emojipedia vendor/version pages.
// Each target is scraped via `${baseUrl}/new` (preferred) and skipped if unavailable.

export const TARGETS = [
  // Apple (iOS)
  {
    vendorKey: "apple_ios",
    vendorSlug: "apple",
    versionSlug: "ios-9.0",
    os_version: "iOS_9.0",
    release_date: "09 September 2015",
  },
  {
    vendorKey: "apple_ios",
    vendorSlug: "apple",
    versionSlug: "ios-9.2",
    os_version: "iOS_9.2",
    release_date: null,
  },
  {
    vendorKey: "apple_ios",
    vendorSlug: "apple",
    versionSlug: "ios-9.3",
    os_version: "iOS_9.3",
    release_date: null,
  },

  {
    vendorKey: "apple_ios",
    vendorSlug: "apple",
    versionSlug: "ios-10.0",
    os_version: "iOS_10.0",
    release_date: "13 September 2016",
  },
  {
    vendorKey: "apple_ios",
    vendorSlug: "apple",
    versionSlug: "ios-10.2",
    os_version: "iOS_10.2",
    release_date: null,
  },
  {
    vendorKey: "apple_ios",
    vendorSlug: "apple",
    versionSlug: "ios-10.3",
    os_version: "iOS_10.3",
    release_date: null,
  },

  {
    vendorKey: "apple_ios",
    vendorSlug: "apple",
    versionSlug: "ios-11.1",
    os_version: "iOS_11.1",
    release_date: "31 October 2017",
  },
  {
    vendorKey: "apple_ios",
    vendorSlug: "apple",
    versionSlug: "ios-11.2",
    os_version: "iOS_11.2",
    release_date: null,
  },
  {
    vendorKey: "apple_ios",
    vendorSlug: "apple",
    versionSlug: "ios-11.3",
    os_version: "iOS_11.3",
    release_date: null,
  },

  {
    vendorKey: "apple_ios",
    vendorSlug: "apple",
    versionSlug: "ios-12.1",
    os_version: "iOS_12.1",
    release_date: "30 October 2018",
  },
  {
    vendorKey: "apple_ios",
    vendorSlug: "apple",
    versionSlug: "ios-12.2",
    os_version: "iOS_12.2",
    release_date: null,
  },

  {
    vendorKey: "apple_ios",
    vendorSlug: "apple",
    versionSlug: "ios-13.1",
    os_version: "iOS_13.1",
    release_date: "24 September 2019",
  },
  {
    vendorKey: "apple_ios",
    vendorSlug: "apple",
    versionSlug: "ios-13.2",
    os_version: "iOS_13.2",
    release_date: null,
  },
  {
    vendorKey: "apple_ios",
    vendorSlug: "apple",
    versionSlug: "ios-13.3",
    os_version: "iOS_13.3",
    release_date: null,
  },

  {
    vendorKey: "apple_ios",
    vendorSlug: "apple",
    versionSlug: "ios-14.2",
    os_version: "iOS_14.2",
    release_date: "05 November 2020",
  },
  {
    vendorKey: "apple_ios",
    vendorSlug: "apple",
    versionSlug: "ios-14.5",
    os_version: "iOS_14.5",
    release_date: null,
  },
  {
    vendorKey: "apple_ios",
    vendorSlug: "apple",
    versionSlug: "ios-14.6",
    os_version: "iOS_14.6",
    release_date: null,
  },

  {
    vendorKey: "apple_ios",
    vendorSlug: "apple",
    versionSlug: "ios-15.4",
    os_version: "iOS_15.4",
    release_date: "14 March 2022",
  },
  {
    vendorKey: "apple_ios",
    vendorSlug: "apple",
    versionSlug: "ios-16.4",
    os_version: "iOS_16.4",
    release_date: "27 March 2023",
  },
  {
    vendorKey: "apple_ios",
    vendorSlug: "apple",
    versionSlug: "ios-17.4",
    os_version: "iOS_17.4",
    release_date: "05 March 2024",
  },
  {
    vendorKey: "apple_ios",
    vendorSlug: "apple",
    versionSlug: "ios-18.4",
    os_version: "iOS_18.4",
    release_date: "31 March 2025",
  },

  // Google (Android)
  {
    vendorKey: "google_android",
    vendorSlug: "google",
    versionSlug: "android-6.0.1",
    os_version: "Android_6.0.1",
    release_date: "07 December 2015",
  },
  {
    vendorKey: "google_android",
    vendorSlug: "google",
    versionSlug: "android-7.0",
    os_version: "Android_7.0",
    release_date: "22 August 2016",
  },
  {
    vendorKey: "google_android",
    vendorSlug: "google",
    versionSlug: "android-7.1",
    os_version: "Android_7.1",
    release_date: "20 October 2016",
  },
  {
    vendorKey: "google_android",
    vendorSlug: "google",
    versionSlug: "android-8.0",
    os_version: "Android_8.0",
    release_date: "21 August 2017",
  },
  {
    vendorKey: "google_android",
    vendorSlug: "google",
    versionSlug: "android-8.1",
    os_version: "Android_8.1",
    release_date: "05 December 2017",
  },
  {
    vendorKey: "google_android",
    vendorSlug: "google",
    versionSlug: "android-10.0",
    os_version: "Android_10.0",
    release_date: "03 September 2019",
  },
  {
    vendorKey: "google_android",
    vendorSlug: "google",
    versionSlug: "android-10.0-march-2020-feature-drop",
    os_version: "Android_10.0_March_2020_Feature_Drop",
    release_date: "02 March 2020",
  },
  {
    vendorKey: "google_android",
    vendorSlug: "google",
    versionSlug: "android-11.0",
    os_version: "Android_11.0",
    release_date: "03 August 2020",
  },
  {
    vendorKey: "google_android",
    vendorSlug: "google",
    versionSlug: "android-11.0-december-2020-feature-drop",
    os_version: "Android_11.0_December_2020_Feature_Drop",
    release_date: "09 December 2020",
  },
  {
    vendorKey: "google_android",
    vendorSlug: "google",
    versionSlug: "android-12.0",
    os_version: "Android_12.0",
    release_date: "04 October 2021",
  },
  {
    vendorKey: "google_android",
    vendorSlug: "google",
    versionSlug: "android-12l",
    os_version: "Android_12L",
    release_date: "27 October 2021",
  },

  // Samsung
  {
    vendorKey: "samsung",
    vendorSlug: "samsung",
    versionSlug: "touchwiz-7.1",
    os_version: "TouchWiz_7.1",
    release_date: "22 September 2016",
  },
  {
    vendorKey: "samsung",
    vendorSlug: "samsung",
    versionSlug: "experience-8.0",
    os_version: "Experience_8.0",
    release_date: "17 January 2017",
  },
  {
    vendorKey: "samsung",
    vendorSlug: "samsung",
    versionSlug: "experience-8.1",
    os_version: "Experience_8.1",
    release_date: "21 April 2017",
  },
  {
    vendorKey: "samsung",
    vendorSlug: "samsung",
    versionSlug: "experience-8.5",
    os_version: "Experience_8.5",
    release_date: "15 September 2017",
  },
  {
    vendorKey: "samsung",
    vendorSlug: "samsung",
    versionSlug: "experience-9.0",
    os_version: "Experience_9.0",
    release_date: "12 February 2018",
  },
  {
    vendorKey: "samsung",
    vendorSlug: "samsung",
    versionSlug: "experience-9.5",
    os_version: "Experience_9.5",
    release_date: "24 August 2018",
  },
  {
    vendorKey: "samsung",
    vendorSlug: "samsung",
    versionSlug: "one-ui-1.5",
    os_version: "OneUI_1.5",
    release_date: "23 August 2019",
  },
  {
    vendorKey: "samsung",
    vendorSlug: "samsung",
    versionSlug: "one-ui-2.1",
    os_version: "OneUI_2.1",
    release_date: "14 February 2020",
  },
  {
    vendorKey: "samsung",
    vendorSlug: "samsung",
    versionSlug: "one-ui-2.5",
    os_version: "OneUI_2.5",
    release_date: "21 August 2020",
  },
  {
    vendorKey: "samsung",
    vendorSlug: "samsung",
    versionSlug: "one-ui-4.0",
    os_version: "OneUI_4.0",
    release_date: "15 November 2021",
  },
  {
    vendorKey: "samsung",
    vendorSlug: "samsung",
    versionSlug: "one-ui-4.0-january-2022",
    os_version: "OneUI_4.0_January_2022",
    release_date: "18 January 2022",
  },
  {
    vendorKey: "samsung",
    vendorSlug: "samsung",
    versionSlug: "one-ui-5.0",
    os_version: "OneUI_5.0",
    release_date: "24 October 2022",
  },
  {
    vendorKey: "samsung",
    vendorSlug: "samsung",
    versionSlug: "one-ui-6.0",
    os_version: "OneUI_6.0",
    release_date: "30 October 2023",
  },
  {
    vendorKey: "samsung",
    vendorSlug: "samsung",
    versionSlug: "one-ui-6.1.1",
    os_version: "OneUI_6.1.1",
    release_date: "10 July 2024",
  },
  {
    vendorKey: "samsung",
    vendorSlug: "samsung",
    versionSlug: "one-ui-7.0",
    os_version: "OneUI_7.0",
    release_date: "22 January 2025",
  },
  {
    vendorKey: "samsung",
    vendorSlug: "samsung",
    versionSlug: "one-ui-7.0-april-2025",
    os_version: "OneUI_7.0_April_2025",
    release_date: "07 April 2025",
  },

  // Microsoft (Windows)
  {
    vendorKey: "microsoft_windows",
    vendorSlug: "microsoft",
    versionSlug: "windows-8.0",
    os_version: "Windows_8.0",
    release_date: "26 October 2012",
  },
  {
    vendorKey: "microsoft_windows",
    vendorSlug: "microsoft",
    versionSlug: "windows-8.1",
    os_version: "Windows_8.1",
    release_date: "17 October 2013",
  },
  {
    vendorKey: "microsoft_windows",
    vendorSlug: "microsoft",
    versionSlug: "windows-10",
    os_version: "Windows_10",
    release_date: "29 July 2015",
  },
  {
    vendorKey: "microsoft_windows",
    vendorSlug: "microsoft",
    versionSlug: "windows-10-anniversary-update",
    os_version: "Windows_10_Anniversary_Update",
    release_date: "02 August 2016",
  },
  {
    vendorKey: "microsoft_windows",
    vendorSlug: "microsoft",
    versionSlug: "windows-10-creators-update",
    os_version: "Windows_10_Creators_Update",
    release_date: "11 April 2017",
  },
  {
    vendorKey: "microsoft_windows",
    vendorSlug: "microsoft",
    versionSlug: "windows-10-fall-creators-update",
    os_version: "Windows_10_Fall_Creators_Update",
    release_date: "17 October 2017",
  },
  {
    vendorKey: "microsoft_windows",
    vendorSlug: "microsoft",
    versionSlug: "windows-10-april-2018-update",
    os_version: "Windows_10_April_2018_Update",
    release_date: "30 April 2018",
  },
  {
    vendorKey: "microsoft_windows",
    vendorSlug: "microsoft",
    versionSlug: "windows-10-october-2018-update",
    os_version: "Windows_10_October_2018_Update",
    release_date: "02 October 2018",
  },
  {
    vendorKey: "microsoft_windows",
    vendorSlug: "microsoft",
    versionSlug: "windows-10-may-2019-update",
    os_version: "Windows_10_May_2019_Update",
    release_date: "21 May 2019",
  },
  {
    vendorKey: "microsoft_windows",
    vendorSlug: "microsoft",
    versionSlug: "windows-11",
    os_version: "Windows_11",
    release_date: "05 October 2021",
  },
  {
    vendorKey: "microsoft_windows",
    vendorSlug: "microsoft",
    versionSlug: "windows-11-november-2021-update",
    os_version: "Windows_11_November_2021_Update",
    release_date: "22 November 2021",
  },
  {
    vendorKey: "microsoft_windows",
    vendorSlug: "microsoft",
    versionSlug: "windows-11-22h2",
    os_version: "Windows_11_22H2",
    release_date: "20 September 2022",
  },
  {
    vendorKey: "microsoft_windows",
    vendorSlug: "microsoft",
    versionSlug: "windows-11-23h2",
    os_version: "Windows_11_23H2",
    release_date: "31 October 2023",
  },
  {
    vendorKey: "microsoft_windows",
    vendorSlug: "microsoft",
    versionSlug: "windows-11-23h2-june-2024-update",
    os_version: "Windows_11_23H2_June_2024_Update",
    release_date: "25 June 2024",
  },
  {
    vendorKey: "microsoft_windows",
    vendorSlug: "microsoft",
    versionSlug: "windows-11-24h2-august-2025-update",
    os_version: "Windows_11_24H2_August_2025_Update",
    release_date: "29 August 2025",
  },
];

export function buildBaseUrl(target) {
  return `https://emojipedia.org/${target.vendorSlug}/${target.versionSlug}`;
}

export function buildNewUrl(target) {
  return `${buildBaseUrl(target)}/new`;
}
